export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const TOGGLE_TASK_COMPLETION = 'TOGGLE_TASK_COMPLETION';
export const CHANGE_TASK = 'CHANGE_TASK';
export const CLEAR_TASKS = 'CLEAR_TASKS';
export const SEARCH_TASKS = 'SEARCH_TASKS';

export const SET_CURRENT_FILTER = 'SET_CURRENT_FILTER';
export const RESET_CURRENT_FILTER = 'RESET_CURRENT_FILTER';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_CURRENT_SEARCH = 'CLEAR_CURRENT_SEARCH';

export const START_TASK_EDITING = 'START_TASK_EDITING';
export const SET_EDITING_TEXT = 'SET_EDITING_TEXT';
export const STOP_TASK_EDITING = 'STOP_TASK_EDITING';
